import {test,expect} from '@playwright/test';
async function start(page){await page.goto('/');await page.locator('[data-bike=mt07]').click();await page.locator('[data-track=meadow]').click();await page.locator('#practice-start').click();await expect(page.locator('#hud')).toBeVisible();await expect(page.locator('#countdown')).toBeHidden({timeout:7000});await page.evaluate(async()=>{const g=await import('/shared/game.js'),r=window.__motoRace,p=g.trackPoint(.04,r.trackId),yaw=g.trackHeading(.04,r.trackId);Object.assign(r.state,p,{yaw,travelYaw:yaw,speed:18,steer:0,health:100,hitCooldown:99,y:g.groundHeight(p.x,p.z,r.trackId)});r.orcs=[];r.combat.projectiles=[];r.applyCamera(true);});}
test('Space selects rear brake, generates drift/marks/audio/lean and recovers on release',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await start(page);
 await page.keyboard.down('ArrowRight');await page.keyboard.down('Space');await expect.poll(()=>page.evaluate(()=>window.__motoRace.inputs())).toEqual({throttle:0,brake:0,rearBrake:1,steer:1});
 await expect.poll(()=>page.evaluate(()=>Math.abs(window.__motoRace.state.slipAngle))).toBeGreaterThan(.15);await expect(page.locator('#surface')).toContainText('ЗАДНИЙ ТОРМОЗ');
 await expect.poll(()=>page.evaluate(()=>window.__motoRace.tyreMarks.mesh.count)).toBeGreaterThan(0);expect(await page.evaluate(()=>window.__motoRace.audioSystem.skidGain.gain.value)).toBeGreaterThan(0);expect(await page.evaluate(()=>window.__motoRace.player.userData.body.rotation.z)).toBeGreaterThan(0);
 await page.screenshot({path:'artifacts/handling-drift-desktop.png'});await page.keyboard.up('Space');await page.keyboard.up('ArrowRight');await page.keyboard.down('ArrowDown');await expect.poll(()=>page.evaluate(()=>Math.abs(window.__motoRace.state.slipAngle))).toBeLessThan(.03);await page.keyboard.up('ArrowDown');
 await page.evaluate(()=>{const r=window.__motoRace;for(let i=0;i<1500;i++)r.tyreMarks.update({...r.state,x:r.state.x+i*.2,speed:10,rearBrake:1,airborne:false,surface:'dirt'},r.gameTime+1+i*.05);});expect(await page.evaluate(()=>window.__motoRace.tyreMarks.mesh.count)).toBe(96);
 await page.keyboard.press('Escape');expect(await page.evaluate(()=>window.__motoRace.tyreMarks)).toBeNull();expect(errors).toEqual([]);
});
test('mobile rear pedal fits portrait/landscape and three fingers release independently without text selection',async({browser})=>{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage();try{
  await start(page);const cdp=await context.newCDPSession(page),point=async(control,id)=>{const b=await page.locator(`[data-control=${control}]`).boundingBox();return {x:Math.round(b.x+b.width/2),y:Math.round(b.y+b.height/2),id,radiusX:4,radiusY:4,force:1};};
  const gas=await point('throttle',1),steer=await point('right',2),rear=await point('rearBrake',3);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[gas,steer,rear]});await expect.poll(()=>page.evaluate(()=>window.__motoRace.inputs())).toEqual({throttle:1,brake:0,rearBrake:1,steer:1});await page.waitForTimeout(350);expect(await page.evaluate(()=>String(getSelection()))).toBe('');
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[rear]});await expect.poll(()=>page.evaluate(()=>window.__motoRace.inputs())).toEqual({throttle:1,brake:0,rearBrake:0,steer:1});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await expect.poll(()=>page.evaluate(()=>window.__motoRace.inputs())).toEqual({throttle:0,brake:0,rearBrake:0,steer:0});
  for(const [width,height]of [[320,640],[390,844],[844,390]]){await page.setViewportSize({width,height});for(const control of ['left','right','brake','rearBrake','throttle']){const b=await page.locator(`[data-control=${control}]`).boundingBox();expect(b.width).toBeGreaterThanOrEqual(44);expect(b.height).toBeGreaterThanOrEqual(44);expect(b.x).toBeGreaterThanOrEqual(0);expect(b.x+b.width).toBeLessThanOrEqual(width);expect(b.y+b.height).toBeLessThanOrEqual(height);}}
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/handling-mobile.png'});
 }finally{await context.close();}
});
test('corner advice warns before a tight bend; stunt hides rear brake and keeps Space as ordinary brake',async({page})=>{
 await start(page);await page.evaluate(async()=>{const g=await import('/shared/game.js'),r=window.__motoRace;r.paused=true;for(let i=0;i<256;i++){const p=g.trackPoint(i/256,r.trackId),s={...r.state,...p,speed:20};if(g.cornerAdvice(s,'clear').brake){Object.assign(r.state,s);r.updateHUD();break;}}});await expect(page.locator('#corner-advice')).toContainText('ТОРМОЗИ');
 await page.keyboard.press('Escape');await page.locator('#practice-mode').selectOption('stunt');await page.locator('#practice-start').click();await expect(page.locator('#race-mode')).toContainText('СТАНТ');await expect(page.locator('[data-control=rearBrake]')).toBeHidden();await page.keyboard.down('Space');expect(await page.evaluate(()=>window.__motoRace.inputs())).toEqual({throttle:0,brake:1,rearBrake:0,steer:0});await page.keyboard.up('Space');
});
