import test from 'node:test';
import assert from 'node:assert/strict';
import {BIKES,trackData,trackPoint,trackHeading,baseHeight,nearestTrack,surfaceAt,createRider,createOrcs,stepOrcs,stepRider,angleDiff,clamp,STEP} from '../shared/game.js';
import {createCombat,stepCombat} from '../shared/combat.js';
import {damageRider} from '../shared/health.js';
function uphillStarts(){const d=trackData('summit'),starts=[];for(let i=0;i<d.TRACK.length;i+=3){const t=i/d.TRACK.length,p=trackPoint(t,'summit'),yaw=trackHeading(t,'summit'),hill=baseHeight(p.x+Math.sin(yaw),p.z+Math.cos(yaw),'summit')-baseHeight(p.x,p.z,'summit');if(hill>.12&&surfaceAt(p.x,p.z,'snow','summit').name==='snow')starts.push({p,yaw,hill});}return starts;}
function drive(s,i,orcs=[],combat=null){const d=trackData('summit'),n=nearestTrack(s.x,s.z,'summit'),p=trackPoint(n.t+4/d.length,'summit'),err=angleDiff(Math.atan2(p.x-s.x,p.z-s.z),s.yaw);stepOrcs(orcs,[s],STEP,i*STEP);if(combat)stepCombat(combat,orcs,[s],STEP,i*STEP);stepRider(s,{throttle:1,steer:clamp(-err*5,-1,1)},STEP,i*STEP,orcs,'snow');}
test('all six motorcycles restart from rest on every sampled snowy uphill without enemies',()=>{const starts=uphillStarts();assert(starts.length>5);for(const bike of BIKES)for(const start of starts){const s=Object.assign(createRider(bike.id,0,'summit'),{...start.p,yaw:start.yaw,speed:0});let peak=0;for(let i=0;i<300;i++){drive(s,i);peak=Math.max(peak,s.speed);}assert(s.distance>10,`${bike.id} stalled at grade ${start.hill}`);assert(peak>3,`${bike.id} did not accelerate uphill`);}});
test('moving melee and ranged hits reduce health but never apply a second stopping multiplier',()=>{for(const type of ['arrow','spear','stone','melee']){const s=createRider();s.speed=12;damageRider(s,type);assert(s.health<100);assert(s.speed>=10,`${type} stopped the rider`);}const s=createRider();s.speed=12;const o={id:0,x:s.x,z:s.z};stepRider(s,{},STEP,0,[o]);assert.equal(s.hits,1);assert(s.speed>10);assert(!s.airborne);});
test('a single chasing orc cannot chain-stop any bike accelerating from rest on the steep snow climb',()=>{const start=uphillStarts().filter(s=>createOrcs(0,'summit').some(o=>Math.hypot(o.x-s.p.x,o.z-s.p.z)<80)).sort((a,b)=>b.hill-a.hill)[0];for(const bike of BIKES){const s=Object.assign(createRider(bike.id,0,'summit'),{...start.p,yaw:start.yaw,id:7});const o=createOrcs(0,'summit').sort((a,b)=>Math.hypot(a.x-s.x,a.z-s.z)-Math.hypot(b.x-s.x,b.z-s.z))[0];assert(Math.hypot(o.x-s.x,o.z-s.z)<100);o.x=s.x;o.z=s.z;const combat=createCombat();let meleeHits=0;for(let i=0;i<600;i++){const before=s.hits;drive(s,i,[o],combat);if(s.hits>before&&s.lastDamage.type==='melee')meleeHits++;}assert(s.health>0,bike.id+' was trapped');assert(meleeHits<=2,bike.id+' took chained melee hits');assert(s.distance>35,bike.id+' could not escape');assert(Math.hypot(s.x-o.x,s.z-o.z)>5,bike.id+' remains in melee range');}});
