import * as T from 'three';
import {arcadeFeatures,oilPuddles} from '../shared/arcade.js';
import {groundHeight} from '../shared/tracks.js';
export function createArcadeView(scene,trackId){
 const root=new T.Group();scene.add(root);const models=new Map(),colors={fuel:0xffbd54,food:0x94d56c,oil:0x70b9e7,boost:0xc29aff};
 for(const p of arcadeFeatures(trackId)){const group=new T.Group();group.position.set(p.x,groundHeight(p.x,p.z,trackId)+.9,p.z);root.add(group);const material=new T.MeshStandardMaterial({color:colors[p.type],metalness:.25,roughness:.4,emissive:colors[p.type],emissiveIntensity:.12});const body=new T.Mesh(p.type==='food'?new T.SphereGeometry(.32,12,8):p.type==='boost'?new T.OctahedronGeometry(.46):new T.BoxGeometry(.55,.65,.25),material);group.add(body);const canvas=document.createElement('canvas');canvas.width=128;canvas.height=64;const ctx=canvas.getContext('2d');ctx.fillStyle='#162b25';ctx.fillRect(0,0,128,64);ctx.fillStyle='#ffffff';ctx.font='bold 32px sans-serif';ctx.textAlign='center';ctx.fillText({fuel:'ГАЗ',oil:'+18',food:'ЕДА',boost:'»»'}[p.type],64,44);const texture=new T.CanvasTexture(canvas);texture.colorSpace=T.SRGBColorSpace;const label=new T.Sprite(new T.SpriteMaterial({map:texture,depthTest:true}));label.position.y=.7;label.scale.set(1.2,.6,1);group.add(label);models.set(p.id,group);}
 for(const p of oilPuddles(trackId)){const patch=new T.Mesh(new T.CircleGeometry(p.radius,32),new T.MeshPhysicalMaterial({color:0x141c2b,metalness:.4,roughness:.12,clearcoat:1,side:T.DoubleSide}));patch.rotation.x=-Math.PI/2;patch.position.set(p.x,groundHeight(p.x,p.z,trackId)+.12,p.z);root.add(patch);}
 return {root,update(world,time){for(const p of world?.items||[]){const m=models.get(p.id);m.visible=p.readyAt<=time;m.rotation.y=time*.8;m.position.y=groundHeight(p.x,p.z,trackId)+1+Math.sin(time*2+p.id)*.15;}},dispose(){root.removeFromParent();root.traverse(o=>{o.geometry?.dispose();o.material?.map?.dispose();o.material?.dispose();});}};
}
