import '@fontsource/manrope/400.css';
import '@fontsource/manrope/600.css';
import '@fontsource/manrope/700.css';
import '@fontsource/manrope/800.css';
import '@fontsource/unbounded/600.css';
import './style.css';
import { BIKES,bikeById,formatTime,VERSION } from '../shared/game.js';
import { Race } from './race.js';
import { Showcase } from './showcase.js';
import { api } from './network.js';
const $=id=>document.getElementById(id);let selected=localStorage.getItem('moto-bike')||'cub',user=null,register=false,rankingLocal=false,backend=false,race,showcase;
if(!BIKES.some(b=>b.id===selected))selected='cub';
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,4500);}
function loadLocal(){try{const a=JSON.parse(localStorage.getItem('moto-laps')||'[]');return Array.isArray(a)?a.filter(e=>e&&BIKES.some(b=>b.id===e.bike)&&Number.isFinite(e.best)&&e.best>0&&Number.isInteger(e.laps)&&e.laps>=0).slice(0,6):[];}catch{return [];}}
function saveLap(bike,seconds,online){if(online)return;const entries=loadLocal();let e=entries.find(e=>e.bike===bike);if(!e){e={bike,best:seconds,laps:0};entries.push(e);}e.best=Math.min(e.best,seconds);e.laps++;e.date=new Date().toISOString();localStorage.setItem('moto-laps',JSON.stringify(entries));}
function selectBike(id){selected=id;localStorage.setItem('moto-bike',id);const b=bikeById(id);showcase?.select(id);$('bike-name').textContent=b.name;$('bike-description').textContent=b.type;$('bike-number').textContent=`0${BIKES.indexOf(b)+1} / ${String(BIKES.length).padStart(2,'0')}`;$('stat-speed').style.width=`${b.maxSpeed/42*100}%`;$('stat-handling').style.width=`${b.handling/1.2*100}%`;$('stat-mud').style.width=`${b.mudGrip*100}%`;for(const button of $('bike-selection').children){const active=button.dataset.bike===id;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));}}
for(const[b,index]of BIKES.map((b,i)=>[b,i])){const button=document.createElement('button');button.className='bike-card';button.dataset.bike=b.id;const number=document.createElement('span');number.className='bike-index';number.textContent=`0${index+1} / ${b.class==='adventure'?'ЭНДУРО':b.class==='underbone'?'КЛАССИКА':b.class==='scooter'?'СКУТЕР':b.class==='naked'?'НЕЙКЕД':'СПОРТ'}`;const name=document.createElement('strong');name.textContent=b.name;const caption=document.createElement('small');caption.textContent=b.id==='himalayan'?'Высокая проходимость':b.id==='exciter'?'Быстрый разгон':b.id==='cub'?'Лёгкий и манёвренный':b.id==='winner'?'Точное управление':'Городской комфорт';button.append(number,name,caption);button.onclick=()=>selectBike(b.id);$('bike-selection').append(button);const option=document.createElement('option');option.value=b.id;option.textContent=b.name;$('ranking-bike').append(option);}
for(const button of document.querySelectorAll('[data-close]'))button.onclick=()=>$(button.dataset.close).close();
for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
function updateAccount(){const account=$('account-open');account.replaceChildren();account.append(document.createTextNode(user?user.nickname:'Войти'));const arrow=document.createElement('span');arrow.textContent='↗';account.append(arrow);}
function showAuth(){const logged=!!user;$('auth-title').textContent=logged?`Аккаунт: ${user.nickname}`:register?'Создать аккаунт':'Войти в аккаунт';$('auth-form').hidden=logged;$('auth-switch').hidden=logged;$('account-details').hidden=!logged;$('auth-error').textContent='';if(logged){$('account-details').replaceChildren();const info=document.createElement('p');info.textContent='Аккаунт готов. Выбирай мотоцикл и заходи в комнату с друзьями.';const logout=document.createElement('button');logout.className='secondary';logout.textContent='Выйти из аккаунта';logout.onclick=async()=>{try{await api.logout();user=null;updateAccount();$('auth-dialog').close();}catch(e){toast(e.message);}};$('account-details').append(info,logout);}else{$('auth-submit').textContent=register?'Создать аккаунт →':'Войти →';$('auth-switch').textContent=register?'Уже есть аккаунт? Войти':'Первый заезд? Создать аккаунт';$('auth-form').elements.password.autocomplete=register?'new-password':'current-password';}if(!$('auth-dialog').open)$('auth-dialog').showModal();}
$('account-open').onclick=showAuth;$('auth-switch').onclick=()=>{register=!register;showAuth();};
$('auth-form').onsubmit=async e=>{e.preventDefault();$('auth-submit').disabled=true;$('auth-error').textContent='';const form=new FormData(e.target);try{user=await api.auth(register?'register':'login',form.get('nickname'),form.get('password'));e.target.reset();updateAccount();$('auth-dialog').close();toast(`Добро пожаловать, ${user.nickname}. Аккаунт готов к заездам.`);}catch(error){$('auth-error').textContent=error.message;}finally{$('auth-submit').disabled=false;}};
$('practice-start').onclick=async()=>{if(!race)return;$('practice-start').disabled=true;try{race.practiceWeather=$('practice-weather').value;race.practiceLaps=Number($('practice-laps').value);await race.start(selected);race.state.best=loadLocal().find(e=>e.bike===selected)?.best||0;}finally{$('practice-start').disabled=false;}};
$('online-open').onclick=()=>{if(!backend){toast('Онлайн-сервер недоступен. Можно начать тренировку.');return;}if(!user){showAuth();return;}$('online-error').textContent='';$('online-dialog').showModal();updateRoomForm();};
$('online-form').onsubmit=async e=>{e.preventDefault();if(!race||!user)return;$('online-submit').disabled=true;$('online-error').textContent='';let connection;try{connection=await api.connect($('room-code').value.toUpperCase(),selected,msg=>race.receive(msg),()=>{if(race.connection?.ws===connection?.ws)race.disconnected();},$('room-weather').value,{mode:$('room-mode').value,laps:Number($('room-laps').value)});if(connection.message.version!==VERSION){connection.ws.close();throw new Error('Версии клиента и сервера не совпадают. Обнови страницу.');}$('online-dialog').close();await race.start(selected,connection);toast(`Комната ${connection.message.room}. Передай этот код друзьям.`);}catch(error){connection?.ws.close();$('online-error').textContent=error.message;}finally{$('online-submit').disabled=false;}};
function updateRoomForm(){const open=$('room-mode').value==='open';$('room-code').required=!open;$('room-laps').disabled=open;$('room-code').placeholder=open?'Пусто — присоединиться к открытой трассе':'Например, DRAGON';}
$('room-mode').onchange=updateRoomForm;
function updateSoundButtons(){if(!race)return;for(const id of ['sound-toggle','race-sound']){const button=$(id);button.textContent=race.sound?'Звук: вкл.':'Звук: выкл.';button.setAttribute('aria-label',race.sound?'Выключить звук':'Включить звук');button.setAttribute('aria-pressed',String(race.sound));}}
function toggleSound(){if(!race)return;race.toggleSound();updateSoundButtons();}$('sound-toggle').onclick=toggleSound;$('race-sound').onclick=toggleSound;
async function renderRanking(){const content=$('ranking-content');content.textContent='Загрузка…';$('global-tab').classList.toggle('active',!rankingLocal);$('local-tab').classList.toggle('active',rankingLocal);const bike=$('ranking-bike').value;let entries;try{entries=rankingLocal?loadLocal().filter(e=>!bike||e.bike===bike).map(e=>({nickname:'Ты · тренировка',bike:e.bike,seconds:e.best,laps:e.laps})).sort((a,b)=>a.seconds-b.seconds):(await api.request(`/leaderboard${bike?'?bike='+encodeURIComponent(bike):''}`)).entries;}catch(error){content.textContent=error.message;return;}content.replaceChildren();$('ranking-note').textContent=rankingLocal?'Локальные результаты хранятся в этом браузере и не входят в онлайн-рейтинг.':'Серверные рекорды: контрольные точки по порядку, время с учётом штрафов.';if(!entries.length){const empty=document.createElement('div');empty.className='empty-state';empty.textContent=rankingLocal?'Пока нет завершённых кругов. Пройди все контрольные точки и финишируй.':'Пока нет онлайн-рекордов. Пройди полный круг в совместном заезде.';content.append(empty);return;}const table=document.createElement('table'),head=table.createTHead().insertRow();for(const label of ['#','Гонщик','Мотоцикл','Кругов','Лучший круг']){const th=document.createElement('th');th.textContent=label;head.append(th);}const body=table.createTBody();entries.forEach((e,i)=>{const row=body.insertRow();for(const value of [i+1,e.nickname,bikeById(e.bike).name,e.laps,formatTime(e.seconds)])row.insertCell().textContent=value;});content.append(table);}
$('leaderboard-open').onclick=()=>{$('ranking-dialog').showModal();renderRanking();};$('global-tab').onclick=()=>{rankingLocal=false;renderRanking();};$('local-tab').onclick=()=>{rankingLocal=true;renderRanking();};$('ranking-bike').onchange=renderRanking;
try{race=new Race({onExit:()=>showcase?.resize(),onLap:saveLap,onNotice:toast});showcase=new Showcase($('bike-canvas'));selectBike(selected);updateSoundButtons();}catch(error){console.error(error);$('fatal').hidden=false;$('fatal').textContent='Не удалось запустить 3D. Для этой игры нужен браузер с WebGL 2. Попробуй Chrome, Edge или Firefox с включённым аппаратным ускорением.';}
async function checkBackend(){try{await api.request('/health');backend=true;$('backend-status').textContent='● Онлайн-сервер доступен';$('backend-status').classList.add('online');try{const result=await api.request('/auth/me');user=result.user;updateAccount();}catch{/* Visitors may practice without signing in. */}}catch{$('backend-status').textContent='● Тренировка доступна · онлайн-сервер не подключён';}}
checkBackend();
