import * as T from 'three';
export function createWeather(scene,sun){
 const count=1200,seed=Array.from({length:count},(_,i)=>({x:((i*16807%997)/997-.5)*52,z:((i*48271%991)/991-.5)*52,y:(i*69621%983)/983*28}));
 const rainGeo=new T.BufferGeometry();rainGeo.setAttribute('position',new T.Float32BufferAttribute(new Float32Array(count*6),3));const rain=new T.LineSegments(rainGeo,new T.LineBasicMaterial({color:0xbcced6,transparent:true,opacity:.45,depthWrite:false}));scene.add(rain);
 const snowGeo=new T.BufferGeometry();snowGeo.setAttribute('position',new T.Float32BufferAttribute(new Float32Array(count*3),3));const snow=new T.Points(snowGeo,new T.ShaderMaterial({transparent:true,depthWrite:false,vertexShader:'void main(){vec4 p=modelViewMatrix*vec4(position,1.0);gl_PointSize=clamp(150.0/-p.z,2.0,10.0);gl_Position=projectionMatrix*p;}',fragmentShader:'void main(){float r=length(gl_PointCoord-.5);if(r>.5)discard;gl_FragColor=vec4(.94,.97,1.,(.5-r)*1.7);}'}));scene.add(snow);
 const originals=new Map(),sky=scene.children.find(o=>o.material?.uniforms?.turbidity);let last=null;
 function setWeather(mode){
  if(last===mode)return;last=mode;if(sky)sky.visible=mode==='clear';scene.background=mode==='clear'?null:new T.Color(mode==='rain'?0x718991:0xb7c8d4);rain.visible=mode==='rain';snow.visible=mode==='snow';sun.intensity=mode==='clear'?2.6:mode==='rain'?.75:1.1;sun.color.set(mode==='clear'?0xffd3a0:0xd1deec);
  scene.fog.color.set(mode==='clear'?0x94a7a0:mode==='rain'?0x6c8489:0xb5c5d1);scene.fog.density=mode==='clear'?.0052:mode==='rain'?.009:.008;
  // Snow/wetness on upward surfaces, with original properties restored for clear skies.
  scene.traverse(o=>{if(!o.isMesh||o.isSkinnedMesh)return;const materials=Array.isArray(o.material)?o.material:[o.material];for(const m of materials){if(!m.isMeshStandardMaterial||!m.map||m.map.isCanvasTexture)continue;if(!originals.has(m))originals.set(m,{color:m.color.clone(),roughness:m.roughness});const original=originals.get(m);m.color.copy(original.color);m.roughness=original.roughness;if(!m.userData.weatherUniform){m.userData.weatherUniform={value:0};m.onBeforeCompile=shader=>{shader.uniforms.uSnow=m.userData.weatherUniform;shader.vertexShader='varying float vSnowSlope;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <beginnormal_vertex>','#include <beginnormal_vertex>\nvec3 snowNormal=objectNormal;\n#ifdef USE_INSTANCING\nsnowNormal=mat3(instanceMatrix)*snowNormal;\n#endif\nvSnowSlope=normalize(mat3(modelMatrix)*snowNormal).y;');shader.fragmentShader='uniform float uSnow;varying float vSnowSlope;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\ndiffuseColor.rgb=mix(diffuseColor.rgb,vec3(.82,.87,.93),uSnow*smoothstep(.25,.75,vSnowSlope));');};m.customProgramCacheKey=()=>'snow-surfaces-v1';m.needsUpdate=true;}m.userData.weatherUniform.value=mode==='snow'?.98:0;if(mode==='rain')m.roughness=Math.max(.22,original.roughness*.48);}});
 }
 return {rain,snow,get mode(){return last;},update(time,state,mode='clear'){setWeather(mode);if(mode==='clear')return;const positions=(mode==='rain'?rainGeo:snowGeo).attributes.position,fall=mode==='rain'?19:2.2;
  for(let i=0;i<count;i++){const p=seed[i],y=(p.y-time*fall%28+28)%28,x=state.x+p.x+Math.sin(time*.6+i)*.35,z=state.z+p.z+Math.sin(time*.4+i)*.3;if(mode==='rain'){positions.setXYZ(i*2,x,state.y+y,z);positions.setXYZ(i*2+1,x-.15,state.y+y+.85,z-.12);}else positions.setXYZ(i,x,state.y+y,z);}positions.needsUpdate=true;
 }};
}
